### ISSUE TITLE
Manager View: Show all cases currently being worked

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#357]
As a manager,
when I navigate to `/dispatch`

I see every case my employees (that share my station ID) are currently working, (designated by the initial of the employee beside it)

Managers and employees should be designated by CSS function.

See the attached design for fields.
[Current and History.pdf](https://github.com/department-of-veterans-affairs/caseflow-certification/files/556820/Current.and.History.pdf)

#### Subtasks related to this base story:
- [x] Create users table. Refactor current user model to persist to DB https://github.com/department-of-veterans-affairs/caseflow-certification/pull/394
- [x] Create appeals table. Refactor current appeals model to persist to DB. Ensure current certification functionality is maintained. https://github.com/department-of-veterans-affairs/caseflow-certification/pull/397
- [x] Create tasks table and model https://github.com/department-of-veterans-affairs/caseflow-certification/pull/398
- [x] Define initial task routes and controller https://github.com/department-of-veterans-affairs/caseflow-certification/pull/402
- [ ] Create nightly background job for creating new tasks. see https://github.com/department-of-veterans-affairs/caseflow-certification/issues/426

**Comment by joofsh** [comment]
@lakohl @shanear Just to make sure I understand the bigger picture, a couple questions about the ticket:

It mentions employees and managers are defined by "CSS function".
  - Is this based on their `roles`? As in the `/dispatch` landing page will be different based on the user's role?

It says that the manager can see every case assigned to a user with the same station id, but I'm not clear how this scales. I imagined there being multiple work queues within the same station.
   - Will this page need to support multiple, separate work queues. Or will the Manager's view be a mixed list of tasks?
   - Specific to the MVP with creating end products, are we separating partial grants and full grants (such as it's performed today), or merging them into one unified work queue? (eg. are we keeping Bill's work flow separate?)
 
The Search & "Show More" functionality; I understand we aren't planning to implement these as part of the MVP, but they impact upfront technical decisions.
  - Do you have a sense of how these would work in a future iteration? Would the "Show More" render more tasks inline or take the user to a different page? 
- Would the search show results inline (maybe as a dropdown) or take the user to a different page?

Links on page. Several things in the design show up in blue, are they clickable? If so, where does it take the manager if they click into a specific task?

CC @mdbenjam

**Comment by shanear** [comment]
> Is this based on their CSS roles? As in the /dispatch landing page will be different based on the user's role?
Yes & yes.

> Will this page need to support multiple, separate work queues. Or will the Manager's view be a mixed list of tasks?
For now there will only be a work queue for AMC end product creation. We can deal with splitting out work queues for different actions when another type of work item is needed (should still be a month or two away).

> Specific to the MVP with creating end products, are we separating partial grants and full grants (such as it's performed today), or merging them into one unified work queue? (eg. are we keeping Bill's work flow separate?)
Good question. I'll let @lakohl answer that one 😄 

> The Search & "Show More" functionality; I understand we aren't planning to implement these as part of the MVP, but they impact upfront technical decisions.
I think I see where your going here. We should have the discussion about possibly incorporating React. However, for this story, I feel like we should list everything out in an erb. That's a pretty negligible amount of work and if we want to convert that to React for search filtering we can still do that.

> Links on page. Several things in the design show up in blue, are they clickable? If so, where does it take the manager if they click into a specific task?
This is a good question for @lakohl, but whatever the answer, it will be captured in a future story.

**Comment by joofsh** [comment]
@shanear 

> Yes & yes.

Okay perfect, that reduces the upfront efforts.

> For now there will only be a work queue for AMC end product creation. We can deal with splitting out work queues for different actions when another type of work item is needed (should still be a month or two away).

Sounds good

> I think I see where your going here. We should have the discussion about possibly incorporating React. However, for this story, I feel like we should list everything out in an erb. That's a pretty negligible amount of work and if we want to convert that to React for search filtering we can still do that.

Yea agreed. ERB can 100% accomplish the goals of the current MVP. We can reassess this in the future.


Good question. I'll let @lakohl answer that one 😄
This is a good question for @lakohl, but whatever the answer, it will be captured in a future story.

> Okay I'll follow up with Lara, thanks!

**Comment by lakohl** [comment]
>Specific to the MVP with creating end products, are we separating partial grants and full grants (such as it's performed today), or merging them into one unified work queue? (eg. are we keeping Bill's work flow separate?)

(Pending research findings) I am thinking no, we do not split these out, but do label them.
@abbyraskin can you see a good reason for not merging them at this point?

>Links on page. Several things in the design show up in blue, are they clickable? If so, where does it take the manager if they click into a specific task?

Good point. I will revisit these in another story. Probably don't need the vet name and their number to both be clickable as they will lead to the same place.

**Comment by abbyraskin** [comment]
@lakohl We need a decision from manager on this (as well as a follow-up with a Claims Assistant - I'm working on scheduling these). The only reason not to merge them completely is that only one employee today processes these grants, so we either need to assign these to his user ID directly, or change today's process at AMC (which, from my understanding, would require some training on the part of other Claims Assistants). The manager I met with didn't feel comfortable making a decision until we spoke with the other manager who has more experience with full grants.
